# Generated by Django 3.1.4 on 2020-12-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_used_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='ordered', max_length=20, verbose_name=(('ordered', 'Ordered'), ('shipped', 'Shipped'), ('arrived', 'Arrived'))),
        ),
    ]
